Network module
golemfactory/golem-js pull request #927
Opened 2024-05-15 13:15 UTC by mgordel

2024-05-22 13:10 UTC, SewerynKras requested changes

2024-05-22 13:10 UTC, SewerynKras commented on src/network/network.module.ts
> +      }
This is really hard to read with all that nesting, what do you think about a refactor to move the logic of finding a free ip to a separate function?
```ts
private getFreeIpInNetwork(network: Network, targetIp?: string): IPv4 {
    if (!targetIp) {
      return network.getFirstAvailableIpAddress();
    }
    const ipv4 = IPv4.fromString(targetIp);
    if (!network.isIpInNetwork(ipv4)) {
      throw new GolemNetworkError(
        `The given IP ('${targetIp}') address must belong to the network ('${network.getNetworkInfo().ip}').`,
        NetworkErrorCode.AddressOutOfRange,
        network.getNetworkInfo(),
      );
    }
    if (!network.isNodeIpUnique(ipv4)) {
      throw new GolemNetworkError(
        `IP '${targetIp.toString()}' has already been assigned in this network.`,
        NetworkErrorCode.AddressAlreadyAssigned,
        network.getNetworkInfo(),
      );
    }
    return ipv4;
  }

  async createNetworkNode(network: Network, nodeId: string, nodeIp?: string): Promise<NetworkNode> {
    if (!network.isNodeIdUnique(nodeId)) {
      throw new GolemNetworkError(
        `Network ID '${nodeId}' has already been assigned in this network.`,
        NetworkErrorCode.AddressAlreadyAssigned,
        network.getNetworkInfo(),
      );
    }
    try {
      const ipv4 = this.getFreeIpInNetwork(network, nodeIp);
      const node = await this.deps.networkApi.createNetworkNode(network, nodeId, ipv4.toString());
      network.addNode(node);
      this.deps.logger.info(`Node has been added to the network.`, { id: nodeId, ip: ipv4.toString() });
      return node;
      //.. rest
```

2024-05-22 13:10 UTC, SewerynKras commented on src/network/network.module.ts
> +        `Unable to add node to network. ${error?.data?.message || error.toString()}`,
you can get a better error message than `error?.data?.message || error.toString()` with `getMessageFromApiError`

2024-05-22 13:10 UTC, SewerynKras commented on src/network/network.module.ts
> +        `Unable to remove network node. ${error}`,
Same as above, `${error}` will not display the response from yagna in case of api error unless you use `getMessageFromApiError`

2024-05-22 13:10 UTC, SewerynKras commented on src/shared/yagna/adapters/network-api-adapter.ts
> +  }
I think calls to yagna api should be wrapped in try-catch blocks and mapped to our domain errors. At least that's what I did in all other adapters

2024-05-22 13:15 UTC, SewerynKras commented
I ran the example a couple times and twice I got this error:
![image](https://github.com/golemfactory/golem-js/assets/34130112/97ee10ad-dd2e-4473-a98c-ec3a245bb00b)
I think there is a race condition between the callback that happens in `oneOf`:
```ts
    // Attach handlers for cleanup after all work's done
    lease.events.once("finalized", async () => {
      if (options?.network && networkNode) {
        await this.network.removeNetworkNode(options.network, networkNode);
      }
      await this.payment.releaseAllocation(allocation);
    });
```
and the network being destroyed with `glm.destroyNetwork`.

2024-05-22 13:27 UTC, SewerynKras commented
If I add artificial delay to the request that removes the node
(fragment of `network.module.ts`)
```ts
 async removeNetworkNode(network: Network, node: NetworkNode): Promise<void> {
    if (!network.hasNode(node)) {
      throw new GolemNetworkError(
        `The network node ${node.id} does not belong to the network`,
        NetworkErrorCode.NodeRemovalFailed,
        network.getNetworkInfo(),
      );
    }
    try {
      await sleep(1, false); // <-----------------------------------
      await this.deps.networkApi.removeNetworkNode(network, node);
      network.removeNode(node);
```
then I get an error 100% of the time. Maybe we should add an async lock to network operations? (add node, remove node, remove network)

2024-05-22 13:32 UTC, mgordel commented
Yes, async lock will be necessary, I was also thinking of making the network state, after remove it would change to `removed` and then for this state node removal would be ignored or only logged with warning

2024-05-23 14:06 UTC, SewerynKras approved these changes

2024-05-23 14:06 UTC, SewerynKras commented on src/network/network.ts
> +  public remove() {
`remove` implies that this does something (like call yagna) but it only sets the state as removed. Maybe we could rename it to something like `markAsRemoved`?

2024-05-23 14:08 UTC, SewerynKras commented
Implementation looks good, if you have the time you can rewrite the example to use `manyOf` instead of creating two demands

2024-05-24 10:25 UTC, merged