Module restructuring
golemfactory/golem-js pull request #936
Opened 2024-05-23 13:14 UTC by grisha87

Introducing changes that align high-level, low-level and experimental modules according to what we agreed to during today's call.

2024-05-23 15:28 UTC, SewerynKras requested changes

2024-05-23 15:28 UTC, SewerynKras commented on src/golem-network.ts
> +import { DataTransferProtocol, DeploymentOptions, GolemDeploymentBuilder } from "./experimental/deployment";
If deployment is moved to experimental then there should be a comment on `GolemNetwork.creteDeploymentBuilder` that it's experimental, or that method should be removed altogether

2024-05-23 15:28 UTC, SewerynKras commented on src/experimental.ts
Experimental modules are now exported in two places, in `src/experimental.ts` and in `src/experimental/index.ts`. 
We should either:
-  delete `src/experimental/index.ts` or
-  replace this file with `export * from './experimental'` or
-  delete this file and change rollup config to use `src/experimental/index.ts`

2024-05-23 15:28 UTC, SewerynKras commented on src/golem-network.ts
> +import { DataTransferProtocol, DeploymentOptions, GolemDeploymentBuilder } from "./experimental/deployment";
Pull changes from beta before doing this because after moving this file to `src/golem-network/` git thinks it's a new file

2024-05-23 17:32 UTC, grisha87 commented on src/experimental.ts
I'm dropping `src/experimental.ts` and adjusting rollup configs.

2024-05-24 07:56 UTC, SewerynKras approved these changes

2024-05-24 08:01 UTC, merged